# Site settings
title: Team Code Error 404
subtitle: / Harmony School of Excellence
email: dalfaro@harmonytx.org
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://team-code-error-404.github.io" # the base hostname & protocol for your site
author:
street_address: 4401 San Francisco Ave. Building B
city: Laredo
state: Tx
zip_code: 78041
country: United States of America
phone: (956) 791-0007

# Social settings
500px_url:
facebook_url: https://www.facebook.com/hselaredo/
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/company/713845/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/HseLaredo
discord_url:
comments_url:
youtube_url:

# Sass building
sass:
    sass_dir: _sass

# Build settings
markdown: kramdown

excerpt_separator: <!--more-->

#Prose Config
prose:
  rooturl: '_posts'
  siteurl: 'https://team-code-error-404.github.io/'
  media: 'assets/images'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /tag
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Date"
          value: "CURRENT_DATETIME"
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "image"
        field:
          element: "text"
          label: "Featured Image"
          value: "assets/images/"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          alterable: "true"
          options:
            - name: "Page"
              value: "page"
            - name: "Featured"
              value: "featured"
